// The canonical routing data this control plane runs on. Every value here is
// loaded from the artifacts arc-orchestrator exports (vendored under
// src/routing-core/generated by `npm run sync:routing-core`); nothing is
// hand-authored in this repository. The loader re-validates the artifacts with
// the shared routing-core validators so a broken sync is reported, never
// silently used.

import policyJson from './routing-core/generated/routing-policy.json';
import registryJson from './routing-core/generated/model-registry.json';
import snapshotJson from './routing-core/generated/capability-snapshot.json';
import artifactsManifest from './routing-core/generated/manifest.json';
import policyMarkdown from './routing-core/generated/arc-model-policy.md?raw';
import syncManifest from './routing-core/MANIFEST.json';
import {
  CAPABILITY_ROUTES,
  aliasBindingsFor,
  parseCapabilitySnapshot,
  policyHasErrors,
  validateModelRegistry,
  validatePolicy,
  type AliasBinding,
  type CapabilityRouteContract,
  type CapabilitySnapshot,
  type ModelDefinition,
  type PolicyIssue,
  type RoutingPolicy,
  type RoutingPolicyDocument,
} from './routing-core/index';
import { compileCandidateStacks } from './routing-core/index';

export interface CanonicalRouting {
  policy: RoutingPolicy;
  source: RoutingPolicyDocument['source'];
  policyDocument: string;
  registry: ModelDefinition[];
  registrySchemaVersion: number;
  snapshot: CapabilitySnapshot;
  capabilityRoutes: CapabilityRouteContract[];
  aliasBindings: AliasBinding[];
  routingCore: string;
  sync: { sourceCommit: string | null; contract: string };
  artifacts: { snapshotVersion: string; policyDigest: string };
  /** Load-time problems; empty on a healthy sync. Shown, never swallowed. */
  issues: PolicyIssue[];
  loadErrors: string[];
}

function load(): CanonicalRouting {
  const document = policyJson as unknown as RoutingPolicyDocument;
  const registry = (registryJson as unknown as { schemaVersion: number; entries: ModelDefinition[] });
  const loadErrors: string[] = [];

  const registryCheck = validateModelRegistry(registry.entries, compileCandidateStacks(document.policy));
  if (!registryCheck.ok) loadErrors.push(...registryCheck.errors);

  // Structural validation only at load; measurement freshness is judged where a
  // decision is made, with the clock injected there.
  const snapshot = parseCapabilitySnapshot(snapshotJson as unknown, { entries: registry.entries, nowMs: 0 });
  if (!snapshot.ok) loadErrors.push(...snapshot.errors);

  const issues = validatePolicy(document.policy, { registry: registry.entries });
  if (policyHasErrors(issues)) loadErrors.push('canonical policy has validation errors');

  const manifest = artifactsManifest as { policy: { digest: string }; snapshotVersion: string };
  if (manifest.policy.digest !== document.source.digest) {
    loadErrors.push(`manifest digest ${manifest.policy.digest} does not match routing-policy.json ${document.source.digest}`);
  }

  return {
    policy: document.policy,
    source: document.source,
    policyDocument: policyMarkdown,
    registry: registry.entries,
    registrySchemaVersion: registry.schemaVersion,
    snapshot: snapshot.ok ? snapshot.snapshot : { schemaVersion: 1, snapshotVersion: 'invalid', bandWidth: 0.25, rungs: [] },
    capabilityRoutes: [...CAPABILITY_ROUTES],
    aliasBindings: aliasBindingsFor(document.policy.routeBindings),
    routingCore: (syncManifest as { routingCore: string | null }).routingCore ?? 'unknown',
    sync: {
      sourceCommit: (syncManifest as { sourceCommit: string | null }).sourceCommit,
      contract: (syncManifest as { contract: string }).contract,
    },
    artifacts: { snapshotVersion: manifest.snapshotVersion, policyDigest: manifest.policy.digest },
    issues,
    loadErrors,
  };
}

export const CANONICAL: CanonicalRouting = load();
